# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import AwareDatetime, Field


class ReceiverSpecOidcProvidersItemValidationsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpecOidcProvidersItemValidationsItem"]:
            return ReceiverSpecOidcProvidersItemValidationsItem

        def build(self) -> "ReceiverSpecOidcProvidersItemValidationsItem":
            return ReceiverSpecOidcProvidersItemValidationsItem(**self._attrs)

        def expression(self, value: str, /) -> Self:
            "Expression is the CEL boolean expression to evaluate."
            return self._set("expression", value)

        def message(self, value: str, /) -> Self:
            "Message is returned to the caller when the expression evaluates to false."
            return self._set("message", value)

    class BuilderContext(
        BuilderContextBase["ReceiverSpecOidcProvidersItemValidationsItem.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpecOidcProvidersItemValidationsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpecOidcProvidersItemValidationsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ReceiverSpecOidcProvidersItemValidationsItem", Builder]:
        return GenericListBuilder[
            ReceiverSpecOidcProvidersItemValidationsItem,
            ReceiverSpecOidcProvidersItemValidationsItem.Builder,
        ]()

    expression: str
    "Expression is the CEL boolean expression to evaluate."
    message: str
    "Message is returned to the caller when the expression evaluates to false."


class ReceiverSpecOidcProvidersItemVariablesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpecOidcProvidersItemVariablesItem"]:
            return ReceiverSpecOidcProvidersItemVariablesItem

        def build(self) -> "ReceiverSpecOidcProvidersItemVariablesItem":
            return ReceiverSpecOidcProvidersItemVariablesItem(**self._attrs)

        def expression(self, value: str, /) -> Self:
            "Expression is the CEL expression that defines the variable value."
            return self._set("expression", value)

        def name(self, value: str, /) -> Self:
            "Name is the variable name; it must be a valid CEL identifier."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["ReceiverSpecOidcProvidersItemVariablesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpecOidcProvidersItemVariablesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpecOidcProvidersItemVariablesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ReceiverSpecOidcProvidersItemVariablesItem", Builder]:
        return GenericListBuilder[
            ReceiverSpecOidcProvidersItemVariablesItem,
            ReceiverSpecOidcProvidersItemVariablesItem.Builder,
        ]()

    expression: str
    "Expression is the CEL expression that defines the variable value."
    name: str
    "Name is the variable name; it must be a valid CEL identifier."


class ReceiverSpecResourcesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpecResourcesItem"]:
            return ReceiverSpecResourcesItem

        def build(self) -> "ReceiverSpecResourcesItem":
            return ReceiverSpecResourcesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent"
            return self._set("api_version", value)

        def filter(self, value: str | None, /) -> Self:
            "Filter is a CEL expression expected to return a boolean that is evaluated\nfor each resource matched by this reference when a webhook is received,\nin addition to the top-level resourceFilter. A reconciliation is requested\nonly when both expressions (when set) return true.\nThe expression can read the resource metadata via \u0027res\u0027 and the webhook\nrequest body via \u0027req\u0027. For generic-oidc receivers, the verified OIDC\ntoken claims are also available via \u0027claims\u0027.\nWhen the expression is specified the controller will parse it and mark\nthe object as terminally failed if the expression is invalid or does not\nreturn a boolean."
            return self._set("filter", value)

        def kind(
            self,
            value: Literal[
                "Bucket",
                "GitRepository",
                "Kustomization",
                "HelmRelease",
                "HelmChart",
                "HelmRepository",
                "ImageRepository",
                "ImagePolicy",
                "ImageUpdateAutomation",
                "OCIRepository",
                "ArtifactGenerator",
                "ExternalArtifact",
            ],
            /,
        ) -> Self:
            "Kind of the referent"
            return self._set("kind", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            'MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.\nMatchLabels requires the name to be set to `*`.'
            return self._set("match_labels", value)

        def name(self, value: str, /) -> Self:
            "Name of the referent\nIf multiple resources are targeted `*` may be set."
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent"
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["ReceiverSpecResourcesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpecResourcesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpecResourcesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ReceiverSpecResourcesItem", Builder]:
        return GenericListBuilder[ReceiverSpecResourcesItem, ReceiverSpecResourcesItem.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent"
    filter: str | None = None
    "Filter is a CEL expression expected to return a boolean that is evaluated\nfor each resource matched by this reference when a webhook is received,\nin addition to the top-level resourceFilter. A reconciliation is requested\nonly when both expressions (when set) return true.\nThe expression can read the resource metadata via \u0027res\u0027 and the webhook\nrequest body via \u0027req\u0027. For generic-oidc receivers, the verified OIDC\ntoken claims are also available via \u0027claims\u0027.\nWhen the expression is specified the controller will parse it and mark\nthe object as terminally failed if the expression is invalid or does not\nreturn a boolean."
    kind: Literal[
        "Bucket",
        "GitRepository",
        "Kustomization",
        "HelmRelease",
        "HelmChart",
        "HelmRepository",
        "ImageRepository",
        "ImagePolicy",
        "ImageUpdateAutomation",
        "OCIRepository",
        "ArtifactGenerator",
        "ExternalArtifact",
    ]
    "Kind of the referent"
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    'MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.\nMatchLabels requires the name to be set to `*`.'
    name: Annotated[str, Field(max_length=253, min_length=1)]
    "Name of the referent\nIf multiple resources are targeted `*` may be set."
    namespace: Annotated[str | None, Field(max_length=253, min_length=1)] = None
    "Namespace of the referent"


class ReceiverSpecSecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpecSecretRef"]:
            return ReceiverSpecSecretRef

        def build(self) -> "ReceiverSpecSecretRef":
            return ReceiverSpecSecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["ReceiverSpecSecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpecSecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpecSecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ReceiverSpecSecretRef", Builder]:
        return GenericListBuilder[ReceiverSpecSecretRef, ReceiverSpecSecretRef.Builder]()

    name: str
    "Name of the referent."


class ReceiverStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverStatusConditionsItem"]:
            return ReceiverStatusConditionsItem

        def build(self) -> "ReceiverStatusConditionsItem":
            return ReceiverStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: AwareDatetime, /) -> Self:
            "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
            return self._set("last_transition_time", value)

        def message(self, value: str, /) -> Self:
            "message is a human readable message indicating details about the transition.\nThis may be an empty string."
            return self._set("message", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
            return self._set("observed_generation", value)

        def reason(self, value: str, /) -> Self:
            "reason contains a programmatic identifier indicating the reason for the condition\u0027s last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
            return self._set("reason", value)

        def status(self, value: Literal["True", "False", "Unknown"], /) -> Self:
            "status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "type of condition in CamelCase or in foo.example.com/CamelCase."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["ReceiverStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ReceiverStatusConditionsItem", Builder]:
        return GenericListBuilder[
            ReceiverStatusConditionsItem, ReceiverStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[AwareDatetime, Field(alias="lastTransitionTime")]
    "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
    message: Annotated[str, Field(max_length=32768)]
    "message is a human readable message indicating details about the transition.\nThis may be an empty string."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration", ge=0)] = None
    "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
    reason: Annotated[
        str,
        Field(
            max_length=1024,
            min_length=1,
            pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
        ),
    ]
    "reason contains a programmatic identifier indicating the reason for the condition\u0027s last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
    status: Literal["True", "False", "Unknown"]
    "status of the condition, one of True, False, Unknown."
    type: Annotated[
        str,
        Field(
            max_length=316,
            pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
        ),
    ]
    "type of condition in CamelCase or in foo.example.com/CamelCase."


class ReceiverStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverStatus"]:
            return ReceiverStatus

        def build(self) -> "ReceiverStatus":
            return ReceiverStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[ReceiverStatusConditionsItem] | None, /
        ) -> "ReceiverStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ReceiverStatusConditionsItem,
                        ReceiverStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ReceiverStatusConditionsItem, ReceiverStatusConditionsItem.Builder
                ]
                | list[ReceiverStatusConditionsItem],
            ],
            /,
        ) -> "ReceiverStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ReceiverStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions holds the conditions for the Receiver."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ReceiverStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def last_handled_reconcile_at(self, value: str | None, /) -> Self:
            "LastHandledReconcileAt holds the value of the most recent\nreconcile request value, so a change of the annotation value\ncan be detected."
            return self._set("last_handled_reconcile_at", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the last observed generation of the Receiver object."
            return self._set("observed_generation", value)

        def webhook_path(self, value: str | None, /) -> Self:
            "WebhookPath is the generated incoming webhook address in the format\nof \u0027/hook/sha256sum(token+name+namespace)\u0027."
            return self._set("webhook_path", value)

    class BuilderContext(BuilderContextBase["ReceiverStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ReceiverStatus", Builder]:
        return GenericListBuilder[ReceiverStatus, ReceiverStatus.Builder]()

    conditions: list[ReceiverStatusConditionsItem] | None = None
    "Conditions holds the conditions for the Receiver."
    last_handled_reconcile_at: Annotated[str | None, Field(alias="lastHandledReconcileAt")] = None
    "LastHandledReconcileAt holds the value of the most recent\nreconcile request value, so a change of the annotation value\ncan be detected."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the last observed generation of the Receiver object."
    webhook_path: Annotated[str | None, Field(alias="webhookPath")] = None
    "WebhookPath is the generated incoming webhook address in the format\nof \u0027/hook/sha256sum(token+name+namespace)\u0027."


class ReceiverSpecOidcProvidersItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpecOidcProvidersItem"]:
            return ReceiverSpecOidcProvidersItem

        def build(self) -> "ReceiverSpecOidcProvidersItem":
            return ReceiverSpecOidcProvidersItem(**self._attrs)

        def audience(self, value: str | None, /) -> Self:
            "Audience is the expected audience (\u0027aud\u0027 claim) for tokens issued by\nthis provider. Defaults to \u0027notification-controller\u0027."
            return self._set("audience", value)

        def issuer_url(self, value: str, /) -> Self:
            "IssuerURL is the OIDC issuer URL used for provider discovery. It must\nmatch the \u0027iss\u0027 claim of tokens issued by this provider."
            return self._set("issuer_url", value)

        @overload
        def validations(
            self,
            value_or_callback: list[ReceiverSpecOidcProvidersItemValidationsItem],
            /,
        ) -> "ReceiverSpecOidcProvidersItem.Builder": ...

        @overload
        def validations(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ReceiverSpecOidcProvidersItemValidationsItem,
                        ReceiverSpecOidcProvidersItemValidationsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ReceiverSpecOidcProvidersItemValidationsItem,
                    ReceiverSpecOidcProvidersItemValidationsItem.Builder,
                ]
                | list[ReceiverSpecOidcProvidersItemValidationsItem],
            ],
            /,
        ) -> "ReceiverSpecOidcProvidersItem.Builder": ...

        @overload
        def validations(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ReceiverSpecOidcProvidersItemValidationsItem.Builder]: ...

        def validations(self, value_or_callback=UNSET, /):
            "Validations is the list of CEL boolean expressions evaluated against the\ntoken claims and the variables. The request is accepted only if all of\nthem evaluate to true; the message of each failing expression is returned\nto the caller.\n\nAt least one validation is required. A valid signature alone does not\nauthorize a request: public issuers issue tokens to any caller on the\nplatform, so the validations must constrain the caller\u0027s identity claims\n(e.g. \u0027repository_owner\u0027 for GitHub Actions)."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ReceiverSpecOidcProvidersItemValidationsItem.Builder]()
                context._parent_builder = self
                context._field_name = "validations"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ReceiverSpecOidcProvidersItemValidationsItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("validations", value)

        @overload
        def variables(
            self,
            value_or_callback: list[ReceiverSpecOidcProvidersItemVariablesItem] | None,
            /,
        ) -> "ReceiverSpecOidcProvidersItem.Builder": ...

        @overload
        def variables(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ReceiverSpecOidcProvidersItemVariablesItem,
                        ReceiverSpecOidcProvidersItemVariablesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ReceiverSpecOidcProvidersItemVariablesItem,
                    ReceiverSpecOidcProvidersItemVariablesItem.Builder,
                ]
                | list[ReceiverSpecOidcProvidersItemVariablesItem],
            ],
            /,
        ) -> "ReceiverSpecOidcProvidersItem.Builder": ...

        @overload
        def variables(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ReceiverSpecOidcProvidersItemVariablesItem.Builder]: ...

        def variables(self, value_or_callback=UNSET, /):
            "Variables is an optional list of named CEL expressions, evaluated in order\nand exposed as \u0027vars.\u003cname\u003e\u0027. Each expression can read the token claims\nvia \u0027claims\u0027 and any variable defined before it. Use it to share\nsub-expressions across validations."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ReceiverSpecOidcProvidersItemVariablesItem.Builder]()
                context._parent_builder = self
                context._field_name = "variables"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ReceiverSpecOidcProvidersItemVariablesItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("variables", value)

    class BuilderContext(BuilderContextBase["ReceiverSpecOidcProvidersItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpecOidcProvidersItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpecOidcProvidersItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ReceiverSpecOidcProvidersItem", Builder]:
        return GenericListBuilder[
            ReceiverSpecOidcProvidersItem, ReceiverSpecOidcProvidersItem.Builder
        ]()

    audience: str | None = None
    "Audience is the expected audience (\u0027aud\u0027 claim) for tokens issued by\nthis provider. Defaults to \u0027notification-controller\u0027."
    issuer_url: Annotated[str, Field(alias="issuerURL", pattern="^https?://")]
    "IssuerURL is the OIDC issuer URL used for provider discovery. It must\nmatch the \u0027iss\u0027 claim of tokens issued by this provider."
    validations: Annotated[list[ReceiverSpecOidcProvidersItemValidationsItem], Field(min_length=1)]
    "Validations is the list of CEL boolean expressions evaluated against the\ntoken claims and the variables. The request is accepted only if all of\nthem evaluate to true; the message of each failing expression is returned\nto the caller.\n\nAt least one validation is required. A valid signature alone does not\nauthorize a request: public issuers issue tokens to any caller on the\nplatform, so the validations must constrain the caller\u0027s identity claims\n(e.g. \u0027repository_owner\u0027 for GitHub Actions)."
    variables: list[ReceiverSpecOidcProvidersItemVariablesItem] | None = None
    "Variables is an optional list of named CEL expressions, evaluated in order\nand exposed as \u0027vars.\u003cname\u003e\u0027. Each expression can read the token claims\nvia \u0027claims\u0027 and any variable defined before it. Use it to share\nsub-expressions across validations."


class ReceiverSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ReceiverSpec"]:
            return ReceiverSpec

        def build(self) -> "ReceiverSpec":
            return ReceiverSpec(**self._attrs)

        def events(self, value: list[str] | None, /) -> Self:
            "Events specifies the list of event types to handle,\ne.g. \u0027push\u0027 for GitHub or \u0027Push Hook\u0027 for GitLab."
            return self._set("events", value)

        def interval(self, value: str | None, /) -> Self:
            "Interval at which to reconcile the Receiver with its Secret references."
            return self._set("interval", value)

        @overload
        def oidc_providers(
            self, value_or_callback: list[ReceiverSpecOidcProvidersItem] | None, /
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def oidc_providers(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ReceiverSpecOidcProvidersItem,
                        ReceiverSpecOidcProvidersItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ReceiverSpecOidcProvidersItem, ReceiverSpecOidcProvidersItem.Builder
                ]
                | list[ReceiverSpecOidcProvidersItem],
            ],
            /,
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def oidc_providers(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ReceiverSpecOidcProvidersItem.Builder]: ...

        def oidc_providers(self, value_or_callback=UNSET, /):
            "OIDCProviders specifies the OIDC providers used to authenticate incoming\nrequests when Type is \u0027generic-oidc\u0027. The provider whose IssuerURL matches\nthe token\u0027s \u0027iss\u0027 claim is used to verify the token signature, expiration\nand audience, and to evaluate the configured CEL validations against the\ntoken claims."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ReceiverSpecOidcProvidersItem.Builder]()
                context._parent_builder = self
                context._field_name = "oidc_providers"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverSpecOidcProvidersItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("oidc_providers", value)

        def resource_filter(self, value: str | None, /) -> Self:
            "ResourceFilter is a CEL expression expected to return a boolean that is\nevaluated for each resource referenced in the Resources field when a\nwebhook is received. If the expression returns false then the controller\nwill not request a reconciliation for the resource.\nThe expression can read the resource metadata via \u0027res\u0027 and the webhook\nrequest body via \u0027req\u0027. For generic-oidc receivers, the verified OIDC\ntoken claims are also available via \u0027claims\u0027.\nWhen the expression is specified the controller will parse it and mark\nthe object as terminally failed if the expression is invalid or does not\nreturn a boolean."
            return self._set("resource_filter", value)

        @overload
        def resources(
            self, value_or_callback: list[ReceiverSpecResourcesItem], /
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def resources(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[ReceiverSpecResourcesItem, ReceiverSpecResourcesItem.Builder]],
                GenericListBuilder[ReceiverSpecResourcesItem, ReceiverSpecResourcesItem.Builder]
                | list[ReceiverSpecResourcesItem],
            ],
            /,
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def resources(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ReceiverSpecResourcesItem.Builder]: ...

        def resources(self, value_or_callback=UNSET, /):
            "A list of resources to be notified about changes."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ReceiverSpecResourcesItem.Builder]()
                context._parent_builder = self
                context._field_name = "resources"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverSpecResourcesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("resources", value)

        @overload
        def secret_ref(
            self, value_or_callback: ReceiverSpecSecretRef | None, /
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def secret_ref(
            self,
            value_or_callback: Callable[
                [ReceiverSpecSecretRef.Builder],
                ReceiverSpecSecretRef.Builder | ReceiverSpecSecretRef,
            ],
            /,
        ) -> "ReceiverSpec.Builder": ...

        @overload
        def secret_ref(
            self, value_or_callback: Never = ...
        ) -> "ReceiverSpecSecretRef.BuilderContext": ...

        def secret_ref(self, value_or_callback=UNSET, /):
            "SecretRef specifies the Secret containing the token used\nto validate the payload authenticity. The Secret must contain a \u0027token\u0027\nkey. For GCR receivers, the Secret must also contain an \u0027email\u0027 key\nwith the IAM service account email configured on the Pub/Sub push\nsubscription, and an \u0027audience\u0027 key with the expected OIDC token audience.\n\nRequired for all receiver types except \u0027generic-oidc\u0027, which authenticates\nrequests using the OIDC token instead and must not set this field."
            if self._in_context and value_or_callback is UNSET:
                context = ReceiverSpecSecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverSpecSecretRef.builder())
                if isinstance(output, ReceiverSpecSecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret_ref", value)

        def suspend(self, value: bool | None, /) -> Self:
            "Suspend tells the controller to suspend subsequent\nevents handling for this receiver."
            return self._set("suspend", value)

        def type(
            self,
            value: Literal[
                "generic",
                "generic-hmac",
                "generic-oidc",
                "github",
                "gitlab",
                "bitbucket",
                "harbor",
                "dockerhub",
                "quay",
                "gcr",
                "nexus",
                "acr",
                "cdevents",
            ],
            /,
        ) -> Self:
            "Type of webhook sender, used to determine\nthe validation procedure and payload deserialization."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["ReceiverSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ReceiverSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ReceiverSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ReceiverSpec", Builder]:
        return GenericListBuilder[ReceiverSpec, ReceiverSpec.Builder]()

    events: list[str] | None = None
    "Events specifies the list of event types to handle,\ne.g. \u0027push\u0027 for GitHub or \u0027Push Hook\u0027 for GitLab."
    interval: Annotated[str | None, Field(pattern="^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$")] = "10m"
    "Interval at which to reconcile the Receiver with its Secret references."
    oidc_providers: Annotated[
        list[ReceiverSpecOidcProvidersItem] | None, Field(alias="oidcProviders")
    ] = None
    "OIDCProviders specifies the OIDC providers used to authenticate incoming\nrequests when Type is \u0027generic-oidc\u0027. The provider whose IssuerURL matches\nthe token\u0027s \u0027iss\u0027 claim is used to verify the token signature, expiration\nand audience, and to evaluate the configured CEL validations against the\ntoken claims."
    resource_filter: Annotated[str | None, Field(alias="resourceFilter")] = None
    "ResourceFilter is a CEL expression expected to return a boolean that is\nevaluated for each resource referenced in the Resources field when a\nwebhook is received. If the expression returns false then the controller\nwill not request a reconciliation for the resource.\nThe expression can read the resource metadata via \u0027res\u0027 and the webhook\nrequest body via \u0027req\u0027. For generic-oidc receivers, the verified OIDC\ntoken claims are also available via \u0027claims\u0027.\nWhen the expression is specified the controller will parse it and mark\nthe object as terminally failed if the expression is invalid or does not\nreturn a boolean."
    resources: list[ReceiverSpecResourcesItem]
    "A list of resources to be notified about changes."
    secret_ref: Annotated[ReceiverSpecSecretRef | None, Field(alias="secretRef")] = None
    "SecretRef specifies the Secret containing the token used\nto validate the payload authenticity. The Secret must contain a \u0027token\u0027\nkey. For GCR receivers, the Secret must also contain an \u0027email\u0027 key\nwith the IAM service account email configured on the Pub/Sub push\nsubscription, and an \u0027audience\u0027 key with the expected OIDC token audience.\n\nRequired for all receiver types except \u0027generic-oidc\u0027, which authenticates\nrequests using the OIDC token instead and must not set this field."
    suspend: bool | None = None
    "Suspend tells the controller to suspend subsequent\nevents handling for this receiver."
    type: Literal[
        "generic",
        "generic-hmac",
        "generic-oidc",
        "github",
        "gitlab",
        "bitbucket",
        "harbor",
        "dockerhub",
        "quay",
        "gcr",
        "nexus",
        "acr",
        "cdevents",
    ]
    "Type of webhook sender, used to determine\nthe validation procedure and payload deserialization."


class Receiver(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "receivers",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Receiver"]:
            return Receiver

        def build(self) -> "Receiver":
            return Receiver(**self._attrs)

        def api_version(self, value: Literal["notification.toolkit.fluxcd.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Receiver"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Receiver.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Receiver.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: ReceiverSpec | None, /) -> "Receiver.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [ReceiverSpec.Builder], ReceiverSpec.Builder | ReceiverSpec
            ],
            /,
        ) -> "Receiver.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "ReceiverSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ReceiverSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverSpec.builder())
                if isinstance(output, ReceiverSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: ReceiverStatus | None, /) -> "Receiver.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [ReceiverStatus.Builder], ReceiverStatus.Builder | ReceiverStatus
            ],
            /,
        ) -> "Receiver.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "ReceiverStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ReceiverStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ReceiverStatus.builder())
                if isinstance(output, ReceiverStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["Receiver.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Receiver.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Receiver."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Receiver", Builder]:
        return GenericListBuilder[Receiver, Receiver.Builder]()

    api_version: Annotated[
        Literal["notification.toolkit.fluxcd.io/v1"], Field(alias="apiVersion")
    ] = "notification.toolkit.fluxcd.io/v1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Receiver"] = "Receiver"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: ReceiverSpec | None = None
    status: ReceiverStatus | None = None
