# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class AlertSpecEventSourcesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["AlertSpecEventSourcesItem"]:
            return AlertSpecEventSourcesItem

        def build(self) -> "AlertSpecEventSourcesItem":
            return AlertSpecEventSourcesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent"
            return self._set("api_version", value)

        def kind(
            self,
            value: Literal[
                "Bucket",
                "GitRepository",
                "Kustomization",
                "HelmRelease",
                "HelmChart",
                "HelmRepository",
                "ImageRepository",
                "ImagePolicy",
                "ImageUpdateAutomation",
                "OCIRepository",
            ],
            /,
        ) -> Self:
            "Kind of the referent"
            return self._set("kind", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            'MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.\nMatchLabels requires the name to be set to `*`.'
            return self._set("match_labels", value)

        def name(self, value: str, /) -> Self:
            "Name of the referent\nIf multiple resources are targeted `*` may be set."
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent"
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["AlertSpecEventSourcesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = AlertSpecEventSourcesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for AlertSpecEventSourcesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["AlertSpecEventSourcesItem", Builder]:
        return GenericListBuilder[AlertSpecEventSourcesItem, AlertSpecEventSourcesItem.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent"
    kind: Literal[
        "Bucket",
        "GitRepository",
        "Kustomization",
        "HelmRelease",
        "HelmChart",
        "HelmRepository",
        "ImageRepository",
        "ImagePolicy",
        "ImageUpdateAutomation",
        "OCIRepository",
    ]
    "Kind of the referent"
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    'MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.\nMatchLabels requires the name to be set to `*`.'
    name: Annotated[str, Field(max_length=53, min_length=1)]
    "Name of the referent\nIf multiple resources are targeted `*` may be set."
    namespace: Annotated[str | None, Field(max_length=53, min_length=1)] = None
    "Namespace of the referent"


class AlertSpecProviderRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["AlertSpecProviderRef"]:
            return AlertSpecProviderRef

        def build(self) -> "AlertSpecProviderRef":
            return AlertSpecProviderRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["AlertSpecProviderRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = AlertSpecProviderRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for AlertSpecProviderRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["AlertSpecProviderRef", Builder]:
        return GenericListBuilder[AlertSpecProviderRef, AlertSpecProviderRef.Builder]()

    name: str
    "Name of the referent."


class ProviderSpecCertSecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ProviderSpecCertSecretRef"]:
            return ProviderSpecCertSecretRef

        def build(self) -> "ProviderSpecCertSecretRef":
            return ProviderSpecCertSecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["ProviderSpecCertSecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ProviderSpecCertSecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ProviderSpecCertSecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ProviderSpecCertSecretRef", Builder]:
        return GenericListBuilder[ProviderSpecCertSecretRef, ProviderSpecCertSecretRef.Builder]()

    name: str
    "Name of the referent."


class ProviderSpecSecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ProviderSpecSecretRef"]:
            return ProviderSpecSecretRef

        def build(self) -> "ProviderSpecSecretRef":
            return ProviderSpecSecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["ProviderSpecSecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ProviderSpecSecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ProviderSpecSecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ProviderSpecSecretRef", Builder]:
        return GenericListBuilder[ProviderSpecSecretRef, ProviderSpecSecretRef.Builder]()

    name: str
    "Name of the referent."


class AlertSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["AlertSpec"]:
            return AlertSpec

        def build(self) -> "AlertSpec":
            return AlertSpec(**self._attrs)

        def event_metadata(self, value: dict[str, str] | None, /) -> Self:
            "EventMetadata is an optional field for adding metadata to events dispatched by the\ncontroller. This can be used for enhancing the context of the event. If a field\nwould override one already present on the original event as generated by the emitter,\nthen the override doesn\u0027t happen, i.e. the original value is preserved, and an info\nlog is printed."
            return self._set("event_metadata", value)

        def event_severity(self, value: Literal["info", "error"] | None, /) -> Self:
            "EventSeverity specifies how to filter events based on severity.\nIf set to \u0027info\u0027 no events will be filtered."
            return self._set("event_severity", value)

        @overload
        def event_sources(
            self, value_or_callback: list[AlertSpecEventSourcesItem], /
        ) -> "AlertSpec.Builder": ...

        @overload
        def event_sources(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[AlertSpecEventSourcesItem, AlertSpecEventSourcesItem.Builder]],
                GenericListBuilder[AlertSpecEventSourcesItem, AlertSpecEventSourcesItem.Builder]
                | list[AlertSpecEventSourcesItem],
            ],
            /,
        ) -> "AlertSpec.Builder": ...

        @overload
        def event_sources(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[AlertSpecEventSourcesItem.Builder]: ...

        def event_sources(self, value_or_callback=UNSET, /):
            "EventSources specifies how to filter events based\non the involved object kind, name and namespace."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[AlertSpecEventSourcesItem.Builder]()
                context._parent_builder = self
                context._field_name = "event_sources"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(AlertSpecEventSourcesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("event_sources", value)

        def exclusion_list(self, value: list[str] | None, /) -> Self:
            "ExclusionList specifies a list of Golang regular expressions\nto be used for excluding messages."
            return self._set("exclusion_list", value)

        def inclusion_list(self, value: list[str] | None, /) -> Self:
            "InclusionList specifies a list of Golang regular expressions\nto be used for including messages."
            return self._set("inclusion_list", value)

        @overload
        def provider_ref(
            self, value_or_callback: AlertSpecProviderRef, /
        ) -> "AlertSpec.Builder": ...

        @overload
        def provider_ref(
            self,
            value_or_callback: Callable[
                [AlertSpecProviderRef.Builder],
                AlertSpecProviderRef.Builder | AlertSpecProviderRef,
            ],
            /,
        ) -> "AlertSpec.Builder": ...

        @overload
        def provider_ref(
            self, value_or_callback: Never = ...
        ) -> "AlertSpecProviderRef.BuilderContext": ...

        def provider_ref(self, value_or_callback=UNSET, /):
            "ProviderRef specifies which Provider this Alert should use."
            if self._in_context and value_or_callback is UNSET:
                context = AlertSpecProviderRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "provider_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(AlertSpecProviderRef.builder())
                if isinstance(output, AlertSpecProviderRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("provider_ref", value)

        def summary(self, value: str | None, /) -> Self:
            "Summary holds a short description of the impact and affected cluster.\nDeprecated: Use EventMetadata instead."
            return self._set("summary", value)

        def suspend(self, value: bool | None, /) -> Self:
            "Suspend tells the controller to suspend subsequent\nevents handling for this Alert."
            return self._set("suspend", value)

    class BuilderContext(BuilderContextBase["AlertSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = AlertSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for AlertSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["AlertSpec", Builder]:
        return GenericListBuilder[AlertSpec, AlertSpec.Builder]()

    event_metadata: Annotated[dict[str, str] | None, Field(alias="eventMetadata")] = None
    "EventMetadata is an optional field for adding metadata to events dispatched by the\ncontroller. This can be used for enhancing the context of the event. If a field\nwould override one already present on the original event as generated by the emitter,\nthen the override doesn\u0027t happen, i.e. the original value is preserved, and an info\nlog is printed."
    event_severity: Annotated[Literal["info", "error"] | None, Field(alias="eventSeverity")] = (
        "info"
    )
    "EventSeverity specifies how to filter events based on severity.\nIf set to \u0027info\u0027 no events will be filtered."
    event_sources: Annotated[list[AlertSpecEventSourcesItem], Field(alias="eventSources")]
    "EventSources specifies how to filter events based\non the involved object kind, name and namespace."
    exclusion_list: Annotated[list[str] | None, Field(alias="exclusionList")] = None
    "ExclusionList specifies a list of Golang regular expressions\nto be used for excluding messages."
    inclusion_list: Annotated[list[str] | None, Field(alias="inclusionList")] = None
    "InclusionList specifies a list of Golang regular expressions\nto be used for including messages."
    provider_ref: Annotated[AlertSpecProviderRef, Field(alias="providerRef")]
    "ProviderRef specifies which Provider this Alert should use."
    summary: Annotated[str | None, Field(max_length=255)] = None
    "Summary holds a short description of the impact and affected cluster.\nDeprecated: Use EventMetadata instead."
    suspend: bool | None = None
    "Suspend tells the controller to suspend subsequent\nevents handling for this Alert."


class ProviderSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ProviderSpec"]:
            return ProviderSpec

        def build(self) -> "ProviderSpec":
            return ProviderSpec(**self._attrs)

        def address(self, value: str | None, /) -> Self:
            "Address specifies the endpoint, in a generic sense, to where alerts are sent.\nWhat kind of endpoint depends on the specific Provider type being used.\nFor the generic Provider, for example, this is an HTTP/S address.\nFor other Provider types this could be a project ID or a namespace."
            return self._set("address", value)

        @overload
        def cert_secret_ref(
            self, value_or_callback: ProviderSpecCertSecretRef | None, /
        ) -> "ProviderSpec.Builder": ...

        @overload
        def cert_secret_ref(
            self,
            value_or_callback: Callable[
                [ProviderSpecCertSecretRef.Builder],
                ProviderSpecCertSecretRef.Builder | ProviderSpecCertSecretRef,
            ],
            /,
        ) -> "ProviderSpec.Builder": ...

        @overload
        def cert_secret_ref(
            self, value_or_callback: Never = ...
        ) -> "ProviderSpecCertSecretRef.BuilderContext": ...

        def cert_secret_ref(self, value_or_callback=UNSET, /):
            "CertSecretRef specifies the Secret containing\na PEM-encoded CA certificate (in the `ca.crt` key).\n\nNote: Support for the `caFile` key has\nbeen deprecated."
            if self._in_context and value_or_callback is UNSET:
                context = ProviderSpecCertSecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "cert_secret_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ProviderSpecCertSecretRef.builder())
                if isinstance(output, ProviderSpecCertSecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("cert_secret_ref", value)

        def channel(self, value: str | None, /) -> Self:
            "Channel specifies the destination channel where events should be posted."
            return self._set("channel", value)

        def interval(self, value: str | None, /) -> Self:
            "Interval at which to reconcile the Provider with its Secret references.\nDeprecated and not used in v1beta3."
            return self._set("interval", value)

        def proxy(self, value: str | None, /) -> Self:
            "Proxy the HTTP/S address of the proxy server."
            return self._set("proxy", value)

        @overload
        def secret_ref(
            self, value_or_callback: ProviderSpecSecretRef | None, /
        ) -> "ProviderSpec.Builder": ...

        @overload
        def secret_ref(
            self,
            value_or_callback: Callable[
                [ProviderSpecSecretRef.Builder],
                ProviderSpecSecretRef.Builder | ProviderSpecSecretRef,
            ],
            /,
        ) -> "ProviderSpec.Builder": ...

        @overload
        def secret_ref(
            self, value_or_callback: Never = ...
        ) -> "ProviderSpecSecretRef.BuilderContext": ...

        def secret_ref(self, value_or_callback=UNSET, /):
            "SecretRef specifies the Secret containing the authentication\ncredentials for this Provider."
            if self._in_context and value_or_callback is UNSET:
                context = ProviderSpecSecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ProviderSpecSecretRef.builder())
                if isinstance(output, ProviderSpecSecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret_ref", value)

        def suspend(self, value: bool | None, /) -> Self:
            "Suspend tells the controller to suspend subsequent\nevents handling for this Provider."
            return self._set("suspend", value)

        def timeout(self, value: str | None, /) -> Self:
            "Timeout for sending alerts to the Provider."
            return self._set("timeout", value)

        def type(
            self,
            value: Literal[
                "slack",
                "discord",
                "msteams",
                "rocket",
                "generic",
                "generic-hmac",
                "github",
                "gitlab",
                "gitea",
                "bitbucketserver",
                "bitbucket",
                "azuredevops",
                "googlechat",
                "googlepubsub",
                "webex",
                "sentry",
                "azureeventhub",
                "telegram",
                "lark",
                "matrix",
                "opsgenie",
                "alertmanager",
                "grafana",
                "githubdispatch",
                "pagerduty",
                "datadog",
                "nats",
            ],
            /,
        ) -> Self:
            "Type specifies which Provider implementation to use."
            return self._set("type", value)

        def username(self, value: str | None, /) -> Self:
            "Username specifies the name under which events are posted."
            return self._set("username", value)

    class BuilderContext(BuilderContextBase["ProviderSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ProviderSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ProviderSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ProviderSpec", Builder]:
        return GenericListBuilder[ProviderSpec, ProviderSpec.Builder]()

    address: Annotated[str | None, Field(max_length=2048)] = None
    "Address specifies the endpoint, in a generic sense, to where alerts are sent.\nWhat kind of endpoint depends on the specific Provider type being used.\nFor the generic Provider, for example, this is an HTTP/S address.\nFor other Provider types this could be a project ID or a namespace."
    cert_secret_ref: Annotated[ProviderSpecCertSecretRef | None, Field(alias="certSecretRef")] = (
        None
    )
    "CertSecretRef specifies the Secret containing\na PEM-encoded CA certificate (in the `ca.crt` key).\n\nNote: Support for the `caFile` key has\nbeen deprecated."
    channel: Annotated[str | None, Field(max_length=2048)] = None
    "Channel specifies the destination channel where events should be posted."
    interval: Annotated[str | None, Field(pattern="^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$")] = None
    "Interval at which to reconcile the Provider with its Secret references.\nDeprecated and not used in v1beta3."
    proxy: Annotated[str | None, Field(max_length=2048, pattern="^(http|https)://.*$")] = None
    "Proxy the HTTP/S address of the proxy server."
    secret_ref: Annotated[ProviderSpecSecretRef | None, Field(alias="secretRef")] = None
    "SecretRef specifies the Secret containing the authentication\ncredentials for this Provider."
    suspend: bool | None = None
    "Suspend tells the controller to suspend subsequent\nevents handling for this Provider."
    timeout: Annotated[str | None, Field(pattern="^([0-9]+(\\.[0-9]+)?(ms|s|m))+$")] = None
    "Timeout for sending alerts to the Provider."
    type: Literal[
        "slack",
        "discord",
        "msteams",
        "rocket",
        "generic",
        "generic-hmac",
        "github",
        "gitlab",
        "gitea",
        "bitbucketserver",
        "bitbucket",
        "azuredevops",
        "googlechat",
        "googlepubsub",
        "webex",
        "sentry",
        "azureeventhub",
        "telegram",
        "lark",
        "matrix",
        "opsgenie",
        "alertmanager",
        "grafana",
        "githubdispatch",
        "pagerduty",
        "datadog",
        "nats",
    ]
    "Type specifies which Provider implementation to use."
    username: Annotated[str | None, Field(max_length=2048)] = None
    "Username specifies the name under which events are posted."


class Alert(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "alerts",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Alert"]:
            return Alert

        def build(self) -> "Alert":
            return Alert(**self._attrs)

        def api_version(self, value: Literal["notification.toolkit.fluxcd.io/v1beta3"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Alert"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Alert.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Alert.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: AlertSpec | None, /) -> "Alert.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[AlertSpec.Builder], AlertSpec.Builder | AlertSpec],
            /,
        ) -> "Alert.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "AlertSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = AlertSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(AlertSpec.builder())
                if isinstance(output, AlertSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

    class BuilderContext(BuilderContextBase["Alert.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Alert.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Alert."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Alert", Builder]:
        return GenericListBuilder[Alert, Alert.Builder]()

    api_version: Annotated[
        Literal["notification.toolkit.fluxcd.io/v1beta3"], Field(alias="apiVersion")
    ] = "notification.toolkit.fluxcd.io/v1beta3"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Alert"] = "Alert"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: AlertSpec | None = None


class Provider(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "providers",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Provider"]:
            return Provider

        def build(self) -> "Provider":
            return Provider(**self._attrs)

        def api_version(self, value: Literal["notification.toolkit.fluxcd.io/v1beta3"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Provider"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Provider.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Provider.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: ProviderSpec | None, /) -> "Provider.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [ProviderSpec.Builder], ProviderSpec.Builder | ProviderSpec
            ],
            /,
        ) -> "Provider.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "ProviderSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ProviderSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ProviderSpec.builder())
                if isinstance(output, ProviderSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

    class BuilderContext(BuilderContextBase["Provider.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Provider.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Provider."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Provider", Builder]:
        return GenericListBuilder[Provider, Provider.Builder]()

    api_version: Annotated[
        Literal["notification.toolkit.fluxcd.io/v1beta3"], Field(alias="apiVersion")
    ] = "notification.toolkit.fluxcd.io/v1beta3"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Provider"] = "Provider"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: ProviderSpec | None = None
