# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.fluxcd.helm.v2 import HelmRelease as _Resource6
    from cloudcoil.models.fluxcd.image.v1 import ImagePolicy as _Resource8
    from cloudcoil.models.fluxcd.image.v1 import ImageRepository as _Resource9
    from cloudcoil.models.fluxcd.image.v1 import ImageUpdateAutomation as _Resource10
    from cloudcoil.models.fluxcd.kustomize.v1 import Kustomization as _Resource11
    from cloudcoil.models.fluxcd.notification.v1 import Receiver as _Resource14
    from cloudcoil.models.fluxcd.notification.v1beta3 import Alert as _Resource0
    from cloudcoil.models.fluxcd.notification.v1beta3 import Provider as _Resource13
    from cloudcoil.models.fluxcd.source.v1 import Bucket as _Resource2
    from cloudcoil.models.fluxcd.source.v1 import ExternalArtifact as _Resource3
    from cloudcoil.models.fluxcd.source.v1 import GitRepository as _Resource4
    from cloudcoil.models.fluxcd.source.v1 import HelmChart as _Resource5
    from cloudcoil.models.fluxcd.source.v1 import HelmRepository as _Resource7
    from cloudcoil.models.fluxcd.source.v1 import OCIRepository as _Resource12
    from cloudcoil.models.fluxcd.source_extensions_fluxcd_io.v1beta1 import (
        ArtifactGenerator as _Resource1,
    )

_MODELS = {
    ("Alert", "notification.toolkit.fluxcd.io/v1beta3"): (
        "cloudcoil.models.fluxcd.notification.v1beta3",
        "Alert",
    ),
    ("Alert", ""): ("cloudcoil.models.fluxcd.notification.v1beta3", "Alert"),
    ("ArtifactGenerator", "source.extensions.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.source_extensions_fluxcd_io.v1beta1",
        "ArtifactGenerator",
    ),
    ("ArtifactGenerator", ""): (
        "cloudcoil.models.fluxcd.source_extensions_fluxcd_io.v1beta1",
        "ArtifactGenerator",
    ),
    ("Bucket", "source.toolkit.fluxcd.io/v1"): ("cloudcoil.models.fluxcd.source.v1", "Bucket"),
    ("Bucket", ""): ("cloudcoil.models.fluxcd.source.v1", "Bucket"),
    ("ExternalArtifact", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "ExternalArtifact",
    ),
    ("ExternalArtifact", ""): ("cloudcoil.models.fluxcd.source.v1", "ExternalArtifact"),
    ("GitRepository", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "GitRepository",
    ),
    ("GitRepository", ""): ("cloudcoil.models.fluxcd.source.v1", "GitRepository"),
    ("HelmChart", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "HelmChart",
    ),
    ("HelmChart", ""): ("cloudcoil.models.fluxcd.source.v1", "HelmChart"),
    ("HelmRelease", "helm.toolkit.fluxcd.io/v2"): (
        "cloudcoil.models.fluxcd.helm.v2",
        "HelmRelease",
    ),
    ("HelmRelease", ""): ("cloudcoil.models.fluxcd.helm.v2", "HelmRelease"),
    ("HelmRepository", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "HelmRepository",
    ),
    ("HelmRepository", ""): ("cloudcoil.models.fluxcd.source.v1", "HelmRepository"),
    ("ImagePolicy", "image.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.image.v1",
        "ImagePolicy",
    ),
    ("ImagePolicy", ""): ("cloudcoil.models.fluxcd.image.v1", "ImagePolicy"),
    ("ImageRepository", "image.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.image.v1",
        "ImageRepository",
    ),
    ("ImageRepository", ""): ("cloudcoil.models.fluxcd.image.v1", "ImageRepository"),
    ("ImageUpdateAutomation", "image.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.image.v1",
        "ImageUpdateAutomation",
    ),
    ("ImageUpdateAutomation", ""): ("cloudcoil.models.fluxcd.image.v1", "ImageUpdateAutomation"),
    ("Kustomization", "kustomize.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.kustomize.v1",
        "Kustomization",
    ),
    ("Kustomization", ""): ("cloudcoil.models.fluxcd.kustomize.v1", "Kustomization"),
    ("OCIRepository", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "OCIRepository",
    ),
    ("OCIRepository", ""): ("cloudcoil.models.fluxcd.source.v1", "OCIRepository"),
    ("Provider", "notification.toolkit.fluxcd.io/v1beta3"): (
        "cloudcoil.models.fluxcd.notification.v1beta3",
        "Provider",
    ),
    ("Provider", ""): ("cloudcoil.models.fluxcd.notification.v1beta3", "Provider"),
    ("Receiver", "notification.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.notification.v1",
        "Receiver",
    ),
    ("Receiver", ""): ("cloudcoil.models.fluxcd.notification.v1", "Receiver"),
}


@overload
def get_model(
    kind: Literal["Alert"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta3"]
) -> type[_Resource0]: ...


@overload
def get_model(kind: Literal["Alert"], *, api_version: Literal[""] = "") -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ArtifactGenerator"],
    *,
    api_version: Literal["source.extensions.fluxcd.io/v1beta1"],
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ArtifactGenerator"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Bucket"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(kind: Literal["Bucket"], *, api_version: Literal[""] = "") -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ExternalArtifact"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ExternalArtifact"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["GitRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["GitRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["HelmChart"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(kind: Literal["HelmChart"], *, api_version: Literal[""] = "") -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["HelmRelease"], *, api_version: Literal["helm.toolkit.fluxcd.io/v2"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["HelmRelease"], *, api_version: Literal[""] = ""
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["HelmRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["HelmRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ImagePolicy"], *, api_version: Literal["image.toolkit.fluxcd.io/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ImagePolicy"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ImageRepository"], *, api_version: Literal["image.toolkit.fluxcd.io/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["ImageRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["ImageUpdateAutomation"], *, api_version: Literal["image.toolkit.fluxcd.io/v1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["ImageUpdateAutomation"], *, api_version: Literal[""] = ""
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["Kustomization"], *, api_version: Literal["kustomize.toolkit.fluxcd.io/v1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["Kustomization"], *, api_version: Literal[""] = ""
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["OCIRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["OCIRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["Provider"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta3"]
) -> type[_Resource13]: ...


@overload
def get_model(kind: Literal["Provider"], *, api_version: Literal[""] = "") -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["Receiver"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1"]
) -> type[_Resource14]: ...


@overload
def get_model(kind: Literal["Receiver"], *, api_version: Literal[""] = "") -> type[_Resource14]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
