# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.fluxcd.helm.v2 import HelmRelease as _Resource12
    from cloudcoil.models.fluxcd.helm.v2beta1 import HelmRelease as _Resource13
    from cloudcoil.models.fluxcd.helm.v2beta2 import HelmRelease as _Resource14
    from cloudcoil.models.fluxcd.image.v1beta1 import ImagePolicy as _Resource18
    from cloudcoil.models.fluxcd.image.v1beta1 import ImageRepository as _Resource20
    from cloudcoil.models.fluxcd.image.v1beta1 import ImageUpdateAutomation as _Resource22
    from cloudcoil.models.fluxcd.image.v1beta2 import ImagePolicy as _Resource19
    from cloudcoil.models.fluxcd.image.v1beta2 import ImageRepository as _Resource21
    from cloudcoil.models.fluxcd.image.v1beta2 import ImageUpdateAutomation as _Resource23
    from cloudcoil.models.fluxcd.kustomize.v1 import Kustomization as _Resource24
    from cloudcoil.models.fluxcd.kustomize.v1beta1 import Kustomization as _Resource25
    from cloudcoil.models.fluxcd.kustomize.v1beta2 import Kustomization as _Resource26
    from cloudcoil.models.fluxcd.notification.v1 import Receiver as _Resource31
    from cloudcoil.models.fluxcd.notification.v1beta1 import Alert as _Resource0
    from cloudcoil.models.fluxcd.notification.v1beta1 import Provider as _Resource28
    from cloudcoil.models.fluxcd.notification.v1beta1 import Receiver as _Resource32
    from cloudcoil.models.fluxcd.notification.v1beta2 import Alert as _Resource1
    from cloudcoil.models.fluxcd.notification.v1beta2 import Provider as _Resource29
    from cloudcoil.models.fluxcd.notification.v1beta2 import Receiver as _Resource33
    from cloudcoil.models.fluxcd.notification.v1beta3 import Alert as _Resource2
    from cloudcoil.models.fluxcd.notification.v1beta3 import Provider as _Resource30
    from cloudcoil.models.fluxcd.source.v1 import Bucket as _Resource3
    from cloudcoil.models.fluxcd.source.v1 import GitRepository as _Resource6
    from cloudcoil.models.fluxcd.source.v1 import HelmChart as _Resource9
    from cloudcoil.models.fluxcd.source.v1 import HelmRepository as _Resource15
    from cloudcoil.models.fluxcd.source.v1beta1 import Bucket as _Resource4
    from cloudcoil.models.fluxcd.source.v1beta1 import GitRepository as _Resource7
    from cloudcoil.models.fluxcd.source.v1beta1 import HelmChart as _Resource10
    from cloudcoil.models.fluxcd.source.v1beta1 import HelmRepository as _Resource16
    from cloudcoil.models.fluxcd.source.v1beta2 import Bucket as _Resource5
    from cloudcoil.models.fluxcd.source.v1beta2 import GitRepository as _Resource8
    from cloudcoil.models.fluxcd.source.v1beta2 import HelmChart as _Resource11
    from cloudcoil.models.fluxcd.source.v1beta2 import HelmRepository as _Resource17
    from cloudcoil.models.fluxcd.source.v1beta2 import OCIRepository as _Resource27

_MODELS = {
    ("Alert", "notification.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.notification.v1beta1",
        "Alert",
    ),
    ("Alert", "notification.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.notification.v1beta2",
        "Alert",
    ),
    ("Alert", "notification.toolkit.fluxcd.io/v1beta3"): (
        "cloudcoil.models.fluxcd.notification.v1beta3",
        "Alert",
    ),
    ("Bucket", "source.toolkit.fluxcd.io/v1"): ("cloudcoil.models.fluxcd.source.v1", "Bucket"),
    ("Bucket", "source.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.source.v1beta1",
        "Bucket",
    ),
    ("Bucket", "source.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.source.v1beta2",
        "Bucket",
    ),
    ("GitRepository", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "GitRepository",
    ),
    ("GitRepository", "source.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.source.v1beta1",
        "GitRepository",
    ),
    ("GitRepository", "source.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.source.v1beta2",
        "GitRepository",
    ),
    ("HelmChart", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "HelmChart",
    ),
    ("HelmChart", "source.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.source.v1beta1",
        "HelmChart",
    ),
    ("HelmChart", "source.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.source.v1beta2",
        "HelmChart",
    ),
    ("HelmRelease", "helm.toolkit.fluxcd.io/v2"): (
        "cloudcoil.models.fluxcd.helm.v2",
        "HelmRelease",
    ),
    ("HelmRelease", "helm.toolkit.fluxcd.io/v2beta1"): (
        "cloudcoil.models.fluxcd.helm.v2beta1",
        "HelmRelease",
    ),
    ("HelmRelease", "helm.toolkit.fluxcd.io/v2beta2"): (
        "cloudcoil.models.fluxcd.helm.v2beta2",
        "HelmRelease",
    ),
    ("HelmRepository", "source.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.source.v1",
        "HelmRepository",
    ),
    ("HelmRepository", "source.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.source.v1beta1",
        "HelmRepository",
    ),
    ("HelmRepository", "source.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.source.v1beta2",
        "HelmRepository",
    ),
    ("ImagePolicy", "image.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.image.v1beta1",
        "ImagePolicy",
    ),
    ("ImagePolicy", "image.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.image.v1beta2",
        "ImagePolicy",
    ),
    ("ImageRepository", "image.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.image.v1beta1",
        "ImageRepository",
    ),
    ("ImageRepository", "image.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.image.v1beta2",
        "ImageRepository",
    ),
    ("ImageUpdateAutomation", "image.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.image.v1beta1",
        "ImageUpdateAutomation",
    ),
    ("ImageUpdateAutomation", "image.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.image.v1beta2",
        "ImageUpdateAutomation",
    ),
    ("Kustomization", "kustomize.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.kustomize.v1",
        "Kustomization",
    ),
    ("Kustomization", "kustomize.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.kustomize.v1beta1",
        "Kustomization",
    ),
    ("Kustomization", "kustomize.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.kustomize.v1beta2",
        "Kustomization",
    ),
    ("OCIRepository", "source.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.source.v1beta2",
        "OCIRepository",
    ),
    ("OCIRepository", ""): ("cloudcoil.models.fluxcd.source.v1beta2", "OCIRepository"),
    ("Provider", "notification.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.notification.v1beta1",
        "Provider",
    ),
    ("Provider", "notification.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.notification.v1beta2",
        "Provider",
    ),
    ("Provider", "notification.toolkit.fluxcd.io/v1beta3"): (
        "cloudcoil.models.fluxcd.notification.v1beta3",
        "Provider",
    ),
    ("Receiver", "notification.toolkit.fluxcd.io/v1"): (
        "cloudcoil.models.fluxcd.notification.v1",
        "Receiver",
    ),
    ("Receiver", "notification.toolkit.fluxcd.io/v1beta1"): (
        "cloudcoil.models.fluxcd.notification.v1beta1",
        "Receiver",
    ),
    ("Receiver", "notification.toolkit.fluxcd.io/v1beta2"): (
        "cloudcoil.models.fluxcd.notification.v1beta2",
        "Receiver",
    ),
}


@overload
def get_model(
    kind: Literal["Alert"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Alert"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Alert"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta3"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["Bucket"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Bucket"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["Bucket"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["GitRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["GitRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["GitRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["HelmChart"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["HelmChart"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["HelmChart"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["HelmRelease"], *, api_version: Literal["helm.toolkit.fluxcd.io/v2"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["HelmRelease"], *, api_version: Literal["helm.toolkit.fluxcd.io/v2beta1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["HelmRelease"], *, api_version: Literal["helm.toolkit.fluxcd.io/v2beta2"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["HelmRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["HelmRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["HelmRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["ImagePolicy"], *, api_version: Literal["image.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["ImagePolicy"], *, api_version: Literal["image.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource19]: ...


@overload
def get_model(
    kind: Literal["ImageRepository"], *, api_version: Literal["image.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource20]: ...


@overload
def get_model(
    kind: Literal["ImageRepository"], *, api_version: Literal["image.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource21]: ...


@overload
def get_model(
    kind: Literal["ImageUpdateAutomation"],
    *,
    api_version: Literal["image.toolkit.fluxcd.io/v1beta1"],
) -> type[_Resource22]: ...


@overload
def get_model(
    kind: Literal["ImageUpdateAutomation"],
    *,
    api_version: Literal["image.toolkit.fluxcd.io/v1beta2"],
) -> type[_Resource23]: ...


@overload
def get_model(
    kind: Literal["Kustomization"], *, api_version: Literal["kustomize.toolkit.fluxcd.io/v1"]
) -> type[_Resource24]: ...


@overload
def get_model(
    kind: Literal["Kustomization"], *, api_version: Literal["kustomize.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource25]: ...


@overload
def get_model(
    kind: Literal["Kustomization"], *, api_version: Literal["kustomize.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource26]: ...


@overload
def get_model(
    kind: Literal["OCIRepository"], *, api_version: Literal["source.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource27]: ...


@overload
def get_model(
    kind: Literal["OCIRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource27]: ...


@overload
def get_model(
    kind: Literal["Provider"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource28]: ...


@overload
def get_model(
    kind: Literal["Provider"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource29]: ...


@overload
def get_model(
    kind: Literal["Provider"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta3"]
) -> type[_Resource30]: ...


@overload
def get_model(
    kind: Literal["Receiver"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1"]
) -> type[_Resource31]: ...


@overload
def get_model(
    kind: Literal["Receiver"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta1"]
) -> type[_Resource32]: ...


@overload
def get_model(
    kind: Literal["Receiver"], *, api_version: Literal["notification.toolkit.fluxcd.io/v1beta2"]
) -> type[_Resource33]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
